apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - image: thirtyx/dispatcher:latest
        imagePullPolicy: Always
        name: dispatcher
        ports:
          - containerPort: 80
            hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
