apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test-namespace
  annotations:
    github.com/30x.dispatcher.hosts: |
      {
        "test.k8s.local": {
          "ssl": {
            "certificate": { "valueFrom": {"secretKeyRef" : {"key":"ssl.crt"}}},
            "certificateKey": { "valueFrom": {"secretKeyRef" : {"key":"ssl.key"}}}
          }
        }
      }
  labels:
    github.com/30x.dispatcher.routable: "true"
    github.com/30x.dispatcher.org: "example"
    github.com/30x.dispatcher.env: "test"

---

apiVersion: v1
kind: Secret
metadata:
  name: routing
  namespace: test-namespace
data:
  ssl.crt: YWRtaW4=
  ssl.key: MWYyZDFlMmU2N2Rm

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: test-namespace
  name: nodejs-k8s-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-k8s-env
        github.com/30x.dispatcher.routable: "true"
      annotations:
        github.com/30x.dispatcher.paths: '[{"basePath": "/nodejs", "containerPort": "3000"}]'
    spec:
      containers:
      - name: nodejs-k8s-env
        image: thirtyx/nodejs-k8s-env:latest
        env:
          - name: PORT
            value: "3000"
        ports:
          - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BASE_PATH
            value: /nodejs
